name: 'Generate Sitemap'
description: 'Generates a sitemap.xml file for Angular applications'
inputs:
  script-path:
    description: 'Path to the sitemap generation script'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies for sitemap generation
      shell: bash
      run: |
        # Install any necessary dependencies here
        npm install --no-save fs path
        
    - name: Generate sitemap
      shell: bash
      run: node ${{ inputs.script-path }}