# filepath: .github/actions/create-angular-env/action.yml
name: 'Create Angular Environment Files'
description: 'Generates environment.ts and environment.prod.ts with Firebase config'

inputs:
  environment-path:
    description: 'The path to the environments directory (e.g., apps/my-app/src/environments)'
    required: true
  firebase-api-key:
    description: 'Firebase API Key'
    required: true
  firebase-auth-domain:
    description: 'Firebase Auth Domain'
    required: true
  firebase-project-id:
    description: 'Firebase Project ID'
    required: true
  firebase-storage-bucket:
    description: 'Firebase Storage Bucket'
    required: true
  firebase-messaging-sender-id:
    description: 'Firebase Messaging Sender ID'
    required: true
  firebase-app-id:
    description: 'Firebase App ID'
    required: true
  firebase-measurement-id:
    description: 'Firebase Measurement ID (optional)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Create environments directory if needed
      shell: bash
      run: mkdir -p ${{ inputs.environment-path }}

    - name: Create environment.ts and environment.prod.ts
      shell: bash
      run: |
        # Create or update environment.ts
        echo "export const environment = {" > ${{ inputs.environment-path }}/environment.ts
        echo "  production: false," >> ${{ inputs.environment-path }}/environment.ts
        echo "  firebaseConfig: {" >> ${{ inputs.environment-path }}/environment.ts
        echo "    apiKey: '${{ inputs.firebase-api-key }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    authDomain: '${{ inputs.firebase-auth-domain }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    projectId: '${{ inputs.firebase-project-id }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    storageBucket: '${{ inputs.firebase-storage-bucket }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    messagingSenderId: '${{ inputs.firebase-messaging-sender-id }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    appId: '${{ inputs.firebase-app-id }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "    measurementId: '${{ inputs.firebase-measurement-id }}'," >> ${{ inputs.environment-path }}/environment.ts
        echo "  }" >> ${{ inputs.environment-path }}/environment.ts
        echo "};" >> ${{ inputs.environment-path }}/environment.ts

        # Create or update environment.prod.ts
        echo "export const environment = {" > ${{ inputs.environment-path }}/environment.prod.ts
        echo "  production: true," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "  firebaseConfig: {" >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    apiKey: '${{ inputs.firebase-api-key }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    authDomain: '${{ inputs.firebase-auth-domain }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    projectId: '${{ inputs.firebase-project-id }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    storageBucket: '${{ inputs.firebase-storage-bucket }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    messagingSenderId: '${{ inputs.firebase-messaging-sender-id }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    appId: '${{ inputs.firebase-app-id }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "    measurementId: '${{ inputs.firebase-measurement-id }}'," >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "  }" >> ${{ inputs.environment-path }}/environment.prod.ts
        echo "};" >> ${{ inputs.environment-path }}/environment.prod.ts