name: 'Create Firebase environment.ts'
description: 'Creates Angular environment.ts from prefixed GitHub secrets'
inputs:
  env_file:
    required: true
  api_key:
    required: true
  auth_domain:
    required: true
  project_id:
    required: true
  storage_bucket:
    required: false
  messaging_sender_id:
    required: true
  app_id:
    required: true
  measurement_id:
    required: true
runs:
  using: "composite"
  steps:
    - name: Write environment.ts
      shell: bash
      run: |
        ENV_FILE="${{ inputs.env_file }}"
        mkdir -p "$(dirname "$ENV_FILE")"
        cat > "$ENV_FILE" <<EOF
        export const environment = {
            production: true,
            firebaseConfig: {
                apiKey: "${{ inputs.api_key }}",
                authDomain: "${{ inputs.auth_domain }}",
                projectId: "${{ inputs.project_id }}",
                messagingSenderId: "${{ inputs.messaging_sender_id }}",
                appId: "${{ inputs.app_id }}",
                measurementId: "${{ inputs.measurement_id }}"
            }
        }
        EOF